enableTelemetry: false

enableGlobalCache: false

nodeLinker: node-modules

npmPublishAccess: public

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.4.0.cjs
